### ISSUE TITLE
git-dag hangs indefinitely on start

### ISSUE THREAD

**Issue by Coacher** [git-cola/git-cola#652]
Hello.

I have git-cola @ 9c5473babfcb2e170f4d0c6dcce53abdb24a19a5.
git-dag never launches whatever I do.

Steps to reproduce (any of the following):
- Run `git-dag` from a terminal inside git repository.
- Run `git-dag` from a terminal outside git repository and choose one in the repo select dialogue.
- From a running git-cola window click View->DAG.

Expected results:
git-dag is started.

Actual results:
Nothing happens. There are no errors or crashes. When started from a terminal `git-dag` just silently sits there indefinitely. Removing git-cola configuration from ~/.config doesn't help either.

**Comment by davvid** [comment]
Interesting -- the underlying widgetse being used have not changed so here's a few questions that might help you find a solution.

- Did it work in a previous commit?
  - If so, can the problem be bisected down to a single commit?
- Are you using PyQt5?
- Does it work in PyQt4?
  - You can do `env QT_API=pyqt4 git cola` to force PyQt4 to be used when both are installed
- We use QGraphicsScene and QGraphicsView widgets for rendering.  Do other Qt apps that use these work?  There are various examples [here](http://www.programcreek.com/python/example/52415/PyQt4.QtGui.QGraphicsScene) that you can try. If QGraphicsScene is not working in general then there may be something lower-level going on (e.g. graphics related)
- Are you on Linux, Windows, or Mac?
- Does it get as far as running the `git log` commands?  You can do `env GIT_COLA_TRACE=1 git dag` to make it print the git commands it runs
- "Never launches" literally means that the window is never shown, correct?  If I'm understanding that correctly what it means is that the window never appears, not that the window appears but it stays empty.

**Comment by Coacher** [comment]
I'm using PyQt4. PyQt5 is not installed. All other Qt apps work fine, both Qt4 and Qt5. OS is Gentoo Linux amd64. Raw git commands in terminal work fine, git is 2.11.0. Yes, the git-dag window is never shown. However, repo selection dialogue is shown when git-dag is started outside of git repo.

Here's what happens if I run `env GIT_COLA_TRACE=1 git dag` and choose a local clone of git-cola repo @ 9c5473ba:
```
$ env GIT_COLA_TRACE=1 git dag
git -c diff.suppressBlankEmpty=false config -z --get-all cola.icontheme
git -c diff.suppressBlankEmpty=false config --null --file /home/coacher/.gitconfig --list
kfilemodule(20261) KSambaSharePrivate::findSmbConf: KSambaShare: Could not find smb.conf!
git -c diff.suppressBlankEmpty=false config --null --file /home/coacher/.gitconfig --list
git -c diff.suppressBlankEmpty=false config --null --file /home/coacher/Work/gentoo/python/git-cola/.git/config --list
git -c diff.suppressBlankEmpty=false version
git -c diff.suppressBlankEmpty=false update-index --refresh
git -c diff.suppressBlankEmpty=false ls-files -z --
git -c diff.suppressBlankEmpty=false diff-index --cached -z HEAD --
git -c diff.suppressBlankEmpty=false diff-files -z --
git -c diff.suppressBlankEmpty=false ls-files --exclude-standard -z --others --
git -c diff.suppressBlankEmpty=false rev-parse --symbolic-full-name HEAD
git -c diff.suppressBlankEmpty=false merge-base HEAD origin/master
git -c diff.suppressBlankEmpty=false diff-tree --name-only -r -z --no-commit-id 9c5473babfcb2e170f4d0c6dcce53abdb24a19a5 origin/master
git -c diff.suppressBlankEmpty=false remote
git -c diff.suppressBlankEmpty=false for-each-ref --format=%(refname)
git -c diff.suppressBlankEmpty=false ls-files -z --
git -c diff.suppressBlankEmpty=false show --numstat --no-renames --oneline -z 9c5473babfcb2e170f4d0c6dcce53abdb24a19a5
git -c diff.suppressBlankEmpty=false log --no-abbrev-commit --no-ext-diff --no-color --pretty=format:%b -1 9c5473babfcb2e170f4d0c6dcce53abdb24a19a5 --
git -c diff.suppressBlankEmpty=false diff --unified=3 --no-ext-diff --submodule --no-color --patience 9c5473babfcb2e170f4d0c6dcce53abdb24a19a5~ 9c5473babfcb2e170f4d0c6dcce53abdb24a19a5
```
And it stays like this.

Bisecting would be hard as I very rarely use git-dag and the last time I've used it was a long time ago.
But I'm ready to go this way if nothing else helps.

**Comment by Coacher** [comment]
None of the examples from your link are designed to work out of the box. I don't know PyQt at all. Could you please provide a minimal example? What previous I should test?

**Comment by Coacher** [comment]
```
$ git bisect log
git bisect start
# bad: [9c5473babfcb2e170f4d0c6dcce53abdb24a19a5] grep: protect against bad input
git bisect bad 9c5473babfcb2e170f4d0c6dcce53abdb24a19a5
# good: [9c2c2b336f53af9ea811410dc9cd1b48d7f44bab] git-cola v2.5
git bisect good 9c2c2b336f53af9ea811410dc9cd1b48d7f44bab
# good: [56396f8222272b93a1d1d07ff6c04155614dde9d] qtutils: use QtWidgets.QGridLayout
git bisect good 56396f8222272b93a1d1d07ff6c04155614dde9d
# good: [f6ad89fdfddaaf84ce7ebd33a3aa4616cb1c5257] browse: add "Launch Terminal" action
git bisect good f6ad89fdfddaaf84ce7ebd33a3aa4616cb1c5257
# good: [6a03f9d944d72648efdac3195ae7471311f5a6a9] Merge pull request #645 from judaszszymon/test
git bisect good 6a03f9d944d72648efdac3195ae7471311f5a6a9
# bad: [a62c589b5260b762d407c31788ee55b180641474] Merge branch 'diff-line-numbers'
git bisect bad a62c589b5260b762d407c31788ee55b180641474
# good: [f027e41cc7c293dee30d1676659ff7bfac08586a] doc: update v2.11 release notes draft
git bisect good f027e41cc7c293dee30d1676659ff7bfac08586a
# good: [123fbc0929c9287d5ebb05e46986b7527f0430fc] widgets: unify how dialogs save their settings
git bisect good 123fbc0929c9287d5ebb05e46986b7527f0430fc
# good: [a6faaf531020dfc55274734762baaf5e0577841a] diff: use set_value()
git bisect good a6faaf531020dfc55274734762baaf5e0577841a
# good: [cd40099fde814278530f0941f163b7193966720e] diffparse: add docstrings
git bisect good cd40099fde814278530f0941f163b7193966720e
# good: [f17092617c74c77e750f9855a053abe6a1de69b3] diffparse: add a diff line number parser
git bisect good f17092617c74c77e750f9855a053abe6a1de69b3
# bad: [1cf855679f4dbe5919dd6820c26432aaf848a5a2] diff: teach the diff editor to display line numbers
git bisect bad 1cf855679f4dbe5919dd6820c26432aaf848a5a2
# first bad commit: [1cf855679f4dbe5919dd6820c26432aaf848a5a2] diff: teach the diff editor to display line numbers
```

With this commit I have:
```
git-cola $ git-dag
Traceback (most recent call last):
  File "/usr/bin/git-dag", line 92, in <module>
    sys.exit(main())
  File "/usr/bin/git-dag", line 62, in main
    return args.func(args)
  File "/usr/bin/git-dag", line 87, in cmd_dag
    view = git_dag(context.model, args=args, settings=args.settings)
  File "/usr/share/git-cola/lib/cola/widgets/dag.py", line 43, in git_dag
    view = GitDAG(model, ctx, settings=settings)
  File "/usr/share/git-cola/lib/cola/widgets/dag.py", line 429, in __init__
    self.diffwidget = diff.DiffWidget(notifier, self, is_commit=True)
  File "/usr/share/git-cola/lib/cola/widgets/diff.py", line 677, in __init__
    self.diff = DiffTextEdit(self, is_commit=is_commit, whitespace=False)
  File "/usr/share/git-cola/lib/cola/widgets/diff.py", line 135, in __init__
    VimHintedTextEdit.__init__(self, '', parent=parent)
  File "/usr/share/git-cola/lib/cola/widgets/text.py", line 476, in __init__
    HintedTextEdit.__init__(self, hint, parent=parent, readonly=True)
  File "/usr/share/git-cola/lib/cola/widgets/text.py", line 355, in __init__
    self.hint = HintWidget(self, hint)
  File "/usr/share/git-cola/lib/cola/widgets/text.py", line 270, in __init__
    self.enable(True)
  File "/usr/share/git-cola/lib/cola/widgets/text.py", line 305, in enable
    self._widget.set_value(self.value(), block=True)
  File "/usr/share/git-cola/lib/cola/widgets/text.py", line 362, in set_value
    if value or self.hint.modern:
AttributeError: 'DiffTextEdit' object has no attribute 'hint'
```

**Comment by davvid** [comment]
Try doing `git bisect skip`.  Maybe we can find another one (might not be this one, but we'll see)

**Comment by Coacher** [comment]
Skip what exactly?

**Comment by davvid** [comment]
The `git bisect skip` was intended for the commit above that throws an AttributeError.  It's possible that this commit is related, but I was hoping the bisect could continue by telling it to skip that commit in case it was a different one.

That is a recent commit.  Have you tried the latest master?  That widget was made faster recently, in case it works but was just taking a long time at the time.

**Comment by davvid** [comment]
In case it helps, I just made it so that `git dag` no longer constructs the new diff line number stuff.  This should get it much closer to the state before the line number stuff was added, so it might be worth testing the latest version from github again.

Your bisect was pointing at this new bit of code so if that was related then this should help.

**Comment by Coacher** [comment]
Update to 0f6826d9572cbb833e65edc1c2139433ed7cdc78 doesn't help.

**Comment by Coacher** [comment]
> The git bisect skip was intended for the commit above that throws an AttributeError.

```
$ git bisect log
git bisect start
# bad: [9c5473babfcb2e170f4d0c6dcce53abdb24a19a5] grep: protect against bad input
git bisect bad 9c5473babfcb2e170f4d0c6dcce53abdb24a19a5
# good: [9c2c2b336f53af9ea811410dc9cd1b48d7f44bab] git-cola v2.5
git bisect good 9c2c2b336f53af9ea811410dc9cd1b48d7f44bab
# good: [56396f8222272b93a1d1d07ff6c04155614dde9d] qtutils: use QtWidgets.QGridLayout
git bisect good 56396f8222272b93a1d1d07ff6c04155614dde9d
# good: [f6ad89fdfddaaf84ce7ebd33a3aa4616cb1c5257] browse: add "Launch Terminal" action
git bisect good f6ad89fdfddaaf84ce7ebd33a3aa4616cb1c5257
# good: [6a03f9d944d72648efdac3195ae7471311f5a6a9] Merge pull request #645 from judaszszymon/test
git bisect good 6a03f9d944d72648efdac3195ae7471311f5a6a9
# bad: [a62c589b5260b762d407c31788ee55b180641474] Merge branch 'diff-line-numbers'
git bisect bad a62c589b5260b762d407c31788ee55b180641474
# good: [f027e41cc7c293dee30d1676659ff7bfac08586a] doc: update v2.11 release notes draft
git bisect good f027e41cc7c293dee30d1676659ff7bfac08586a
# good: [123fbc0929c9287d5ebb05e46986b7527f0430fc] widgets: unify how dialogs save their settings
git bisect good 123fbc0929c9287d5ebb05e46986b7527f0430fc
# good: [a6faaf531020dfc55274734762baaf5e0577841a] diff: use set_value()
git bisect good a6faaf531020dfc55274734762baaf5e0577841a
# good: [cd40099fde814278530f0941f163b7193966720e] diffparse: add docstrings
git bisect good cd40099fde814278530f0941f163b7193966720e
# skip: [f17092617c74c77e750f9855a053abe6a1de69b3] diffparse: add a diff line number parser
git bisect skip f17092617c74c77e750f9855a053abe6a1de69b3
# bad: [1cf855679f4dbe5919dd6820c26432aaf848a5a2] diff: teach the diff editor to display line numbers
git bisect bad 1cf855679f4dbe5919dd6820c26432aaf848a5a2
# bad: [34355fbd059f8e4af001599d080051dbad789d97] diffparse: rework tests to import the module
git bisect bad 34355fbd059f8e4af001599d080051dbad789d97
# first bad commit: [34355fbd059f8e4af001599d080051dbad789d97] diffparse: rework tests to import the module
```

**Comment by Coacher** [comment]
Is there anything else I should try/check?

**Comment by laerreal** [comment]
Try check wether a rebase is in progress in the repo. I noticed the DAG freezes just after an interactive rebasing has started. But, I did not investigate the issue yet.

**Comment by Coacher** [comment]
No rebase is in progress.

**Comment by davvid** [comment]
Is there any way we can reproduce this with a public git repo, or something you can share in a public tarball?

If this is a private repo, and something about the shape of the history is relevant, git-fast-export has a feature that can create n copy of your repo that contains no actual content from your repo or any identifying information.  It's a repo anonymizing tool:

https://www.git-scm.com/docs/git-fast-export#_anonymizing

Before we go down that path -- do you obesrve this behavior in all repos?  If so then the repo itself is irrelevant, and that won't help.

**Comment by Coacher** [comment]
This happens with all git repos I have. Most of them are local clones of public repos, e.g. this problem is reproducible with a local clone of git-cola's public repo.

**Comment by Coacher** [comment]
Here's also my ~/.gitconfig:
```
[color]
        ui = auto
[commit]
        gpgSign = true
        verbose = true
[core]
        whitespace = space-before-tab,trailing-space,tabwidth=4
[diff]
        algorithm = histogram
        compactionHeuristic = true
        indentHeuristic = true
        renames = copies
        suppressBlankEmpty = true
[format]
        pretty = fuller
        signature = ""
[interactive]
        diffFilter = diff-highlight
[mergetool]
        keepBackup = false
[pager]
        diff = diff-highlight | less
        show = diff-highlight | less
[push]
        default = current
        gpgSign = if-asked
[rebase]
        missingCommitsCheck = error
[tag]
        sort = version:refname
```

**Comment by onnodb** [comment]
Bizarre. I had the same issue this morning: `git-dag` would hang indefinitely on launch, both on my own repo, as well as on `git-cola`'s own repo. (I'm on Ubuntu 17.04.)

`env GIT_COLA_TRACE=1 ./bin/git-dag` within the `git-cola` repo would produce the same trace as the one shown by Coacher on Jan 28. I tried a `git bisect` session, but didn't get any further, with most tagged releases throwing exceptions.

I then installed PyQt4 dependencies using `sudo apt-get install python-qt4`, and the whole thing suddenly started working --- *both* on Qt5 and Qt4. And it *kept* working after `sudo apt-get remove python-qt4`. So I can't reproduce the issue anymore...

**Comment by Coacher** [comment]
For the record. I only have PyQt4-4.12 installed. PyQt5 was never installed on this machine. I use system-wide (not bundled) QtPy-1.2.1. My problem happens with bundled QtPy as well.

**Comment by Coacher** [comment]
No longer reproducible after updating to PyQt5 and uninstalling PyQt4.

**Comment by davvid** [comment]
Thanks!

**Comment by Skim-x-CAT** [comment]
Today i've reproduced that bug on Manjaro (Arch) fresh install (PyQt5 only). Latest master was used.
```
GIT_COLA_TRACE=1 git-dag
git -c diff.suppressBlankEmpty=false -c log.showSignature=false config --null --file /home/cat/.gitconfig --list
git -c diff.suppressBlankEmpty=false -c log.showSignature=false config --null --file /home/cat/Распрацоўка/Праца/git-cola/.git/config --list
git -c diff.suppressBlankEmpty=false -c log.showSignature=false config -z --get-all --show-origin cola.icontheme
git -c diff.suppressBlankEmpty=false -c log.showSignature=false config --null --file /home/cat/.gitconfig --list
git -c diff.suppressBlankEmpty=false -c log.showSignature=false config --null --file /home/cat/Распрацоўка/Праца/git-cola/.git/config --list
git -c diff.suppressBlankEmpty=false -c log.showSignature=false version
git -c diff.suppressBlankEmpty=false -c log.showSignature=false ls-files -z --
git -c diff.suppressBlankEmpty=false -c log.showSignature=false update-index --refresh
git -c diff.suppressBlankEmpty=false -c log.showSignature=false diff-index --cached -z HEAD --
git -c diff.suppressBlankEmpty=false -c log.showSignature=false diff-files -z --
git -c diff.suppressBlankEmpty=false -c log.showSignature=false ls-files -z --others --exclude-standard --
git -c diff.suppressBlankEmpty=false -c log.showSignature=false rev-parse --symbolic-full-name HEAD
git -c diff.suppressBlankEmpty=false -c log.showSignature=false merge-base HEAD origin/master
git -c diff.suppressBlankEmpty=false -c log.showSignature=false diff-tree --name-only --no-commit-id -r -z a73216cdafc9f038c1b9a9e66283f7261f6a10bf origin/master
git -c diff.suppressBlankEmpty=false -c log.showSignature=false remote
git -c diff.suppressBlankEmpty=false -c log.showSignature=false for-each-ref --format=%(refname) --sort=version:refname
git -c diff.suppressBlankEmpty=false -c log.showSignature=false submodule status
git -c diff.suppressBlankEmpty=false -c log.showSignature=false rev-parse HEAD
git -c diff.suppressBlankEmpty=false -c log.showSignature=false ls-files -z --
git -c diff.suppressBlankEmpty=false -c log.showSignature=false show -z --numstat --oneline --no-renames a73216cdafc9f038c1b9a9e66283f7261f6a10bf
git -c diff.suppressBlankEmpty=false -c log.showSignature=false log --no-color --no-abbrev-commit --no-ext-diff --pretty=format:%b -1 a73216cdafc9f038c1b9a9e66283f7261f6a10bf --
git -c diff.suppressBlankEmpty=false -c log.showSignature=false diff --patience --submodule --no-color --no-ext-diff --unified=3 a73216cdafc9f038c1b9a9e66283f7261f6a10bf~ a73216cdafc9f038c1b9a9e66283f7261f6a10bf
```
Any help with debugging that?

**Comment by Skim-x-CAT** [comment]
And miraculously it got fixed after sometime. :(

**Comment by Realex-fire** [comment]
@Skim-x-CAT 
I got the same problem on opensuse tumbleweed with a clean install of git-cola v3.4.
git-dag started with ~10 attempts ¯\_(ツ)_/¯

**Comment by Realex-fire** [comment]
@Skim-x-CAT
I got the same problem on openSUSE Tumbleweed with a clean install of git-cola v3.4.
git-dag started with ~10 attempts ¯_(ツ)_/¯

**Comment by Realex-fire** [comment]
@Skim-x-CAT
I got the same problem on openSUSE Tumbleweed with a clean install of git-cola v3.4.
git-dag started with ~10 attempts ¯\_(ツ)_/¯

**Comment by Realex-fire** [comment]
@Skim-x-CAT @davvid
I got the same problem on openSUSE Tumbleweed with a clean install of git-cola v3.4.
git-dag started with ~10 attempts ¯\_(ツ)_/¯

**Comment by davvid** [comment]
@Realex-fire that's odd that it's non-deterministic. Can you verify that you're seeing this on the cola repo itself?  If so, this seems environmental or related to the Qt installation.

Are you using Qt4 or Qt5?  You can test that from the cola repo:

```
env QT_API=pyqt4 ./bin/git-cola
env QT_API=pyqt5 ./biin/git-cola
```

That'll let you jump between Qt versions to see if it's related.  Could it maybe be network related?  We do use the gravatar service to load thumbnail images for the commit messages.  I've been meaning to add an "offline" mode that never attempts to use the network.  That shouldn't stall the UI, though, as it happens in the background.  Any clues you have can help us narrow it down.

**Comment by Realex-fire** [comment]
So, I compil and install git-cola from source, but qt4 (4.12.3) does not work properly in my distribution with Cola...
```
  File "/usr/share/git-cola/lib/cola/core.py", line 89, in decode
    decoded = value.decode(enc, errors)
AttributeError: 'QVariant' object has no attribute 'decode'
```
but after starting with qt4, git-dag normally starts with qt5...

I managed to determine the minimum configuration for all successful launches git-dag with qt5:
``` 
{
    "gui_state": {
        "startupdialog": {
            "geometry": "AdnQywABAAAAAAHgAAABDgAABaMAAANUAAAB4gAAATcAAAWhAAADUgAAAAAAAA==", 
            "width": 960, 
            "y": 270, 
            "x": 480, 
            "height": 540
        }, 
        "gitdag": {
            "count": 1000
        }
    }
}
```
if you remove at least a line from this config, qt5 stops working.

**Comment by Realex-fire** [comment]
So, I compil and install git-cola from source, but qt4 (4.12.3) does not work properly in my distribution with Cola...
```
  File "/usr/share/git-cola/lib/cola/core.py", line 89, in decode
    decoded = value.decode(enc, errors)
AttributeError: 'QVariant' object has no attribute 'decode'
```
but after starting with qt4, git-dag normally launches with qt5...

I managed to determine the minimum configuration for all successful launches git-dag with qt5:
``` 
{
    "gui_state": {
        "startupdialog": {
            "geometry": "AdnQywABAAAAAAHgAAABDgAABaMAAANUAAAB4gAAATcAAAWhAAADUgAAAAAAAA==", 
            "width": 960, 
            "y": 270, 
            "x": 480, 
            "height": 540
        }, 
        "gitdag": {
            "count": 1000
        }
    }
}
```
if you remove at least a line from this config, qt5 stops working.

**Comment by Realex-fire** [comment]
So, I compil and install git-cola from source, but qt4 (4.12.3) does not work properly in my distribution with Cola...
```
  File "/usr/share/git-cola/lib/cola/core.py", line 89, in decode
    decoded = value.decode(enc, errors)
AttributeError: 'QVariant' object has no attribute 'decode'
```
but after starting with qt4, git-dag correctly launches with qt5...

I managed to determine the minimum configuration for all successful launches git-dag with qt5:
``` 
{
    "gui_state": {
        "startupdialog": {
            "geometry": "AdnQywABAAAAAAHgAAABDgAABaMAAANUAAAB4gAAATcAAAWhAAADUgAAAAAAAA==", 
            "width": 960, 
            "y": 270, 
            "x": 480, 
            "height": 540
        }, 
        "gitdag": {
            "count": 1000
        }
    }
}
```
if you remove at least a line from this config, qt5 stops working.

**Comment by Realex-fire** [comment]
So, I compil and install git-cola from source, but qt4 (4.12.3) does not work properly in my distribution with Cola...
```
  File "/usr/share/git-cola/lib/cola/core.py", line 89, in decode
    decoded = value.decode(enc, errors)
AttributeError: 'QVariant' object has no attribute 'decode'
```
but after launch with qt4, git-dag correctly launches with qt5...

I managed to determine the minimum configuration for all successful launches git-dag with qt5:
``` 
{
    "gui_state": {
        "startupdialog": {
            "geometry": "AdnQywABAAAAAAHgAAABDgAABaMAAANUAAAB4gAAATcAAAWhAAADUgAAAAAAAA==", 
            "width": 960, 
            "y": 270, 
            "x": 480, 
            "height": 540
        }, 
        "gitdag": {
            "count": 1000
        }
    }
}
```
if you remove at least a line from this config, qt5 stops working.
